# Generated by Django 4.1.3 on 2022-11-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
